version: '2'
services:
  zabbix-server:
    build: .
#    image: r.yfix.net/zabbix-server
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./docker/etc/zabbix/:/etc/zabbix/
      - ./docker/var/log/zabbix/:/var/log/zabbix/
